print("Crée ton personnage !")
nom = input("comment s'appelle ton personnage ?")
âge = input("Quel âge a ton personnage ?")
forces = input("Quelles sont les forces de ton personnage ?")
faiblesses = input("Quelles sont les faiblesse de ton personnage ?")
print("Ton personnage s'appelle ",nom)
print("Ton personnage à ",âge, " ans")
print("forces : ",forces)
print("faiblesses : ",faiblesses)
print(nom, "dit : « Merci de m'avoir crée ! »")
